---
- hosts: all
  gather_facts: yes
  become: true

  tasks:
  - name: Collect fact on remote host
    ansible.builtin.debug:
      var: ansible_facts

#    ansible.builtin.setup:
#      filter: "*"

